// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbabl0E-nsUo9C2UlzE9SntsVVkesfbUg',
    appId: '1:926510339760:web:2e07f638693c045b91cd75',
    messagingSenderId: '926510339760',
    projectId: 'vchatter',
    authDomain: 'vchatter.firebaseapp.com',
    storageBucket: 'vchatter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd2-xazXiGq1F28k3TJ6qJFGVkw7YVegw',
    appId: '1:926510339760:android:1db1ee7bc28839e691cd75',
    messagingSenderId: '926510339760',
    projectId: 'vchatter',
    storageBucket: 'vchatter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyComiNiiuQM6N2_PICqHvYznsxlsCpqnqw',
    appId: '1:926510339760:ios:4d154ddeb01abd1891cd75',
    messagingSenderId: '926510339760',
    projectId: 'vchatter',
    storageBucket: 'vchatter.appspot.com',
    iosClientId: '926510339760-hevqf8s1h40q10u92hcqhp3ul30b0dos.apps.googleusercontent.com',
    iosBundleId: 'com.vortexconsortium.vchatter',
  );
}
